project:
  type: website

website:
  title: "Geospatial Analytics"
  navbar:
    left:
      - text: In-Class Exercises
        menu:
          - text: In-Class Exercise 1
            href: InClassExercise/InClass_Ex01/InClass_Ex01.qmd
            
      - text: Hands-On Exercises
        menu:
          - text: Hands-On Exercise 1
          


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

